services:
  - type: web
    name: campusfix-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AUTH_SECRET_KEY
        sync: false
      - key: INITIAL_HOST_USERNAME
        sync: false
      - key: INITIAL_HOST_PASSWORD
        sync: false
      - key: INITIAL_HOST_NAME
        sync: false
      - key: INITIAL_HOST_EMAIL
        sync: false
      - key: INITIAL_HOST_NETID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: https://vamsi-ns.github.io
      - key: OPENROUTER_API_KEY
        sync: false
